import fs from "node:fs";
import path from "node:path";

const root = import.meta.dirname;
const topicsDir = path.join(root, "topics");
const outPath = path.join(root, "index.html");
const style = fs.readFileSync(path.join(root, "index.css"), "utf8");

function read(file) {
	return fs.existsSync(file) ? fs.readFileSync(file, "utf8") : "";
}

function escapeHtml(text) {
	return text
		.replace(/&/g, "&amp;")
		.replace(/</g, "&lt;")
		.replace(/>/g, "&gt;")
		.replace(/"/g, "&quot;");
}

function inlineMarkdown(text) {
	return escapeHtml(text)
		.replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>")
		.replace(/\*([^*]+)\*/g, "<em>$1</em>")
		.replace(/`([^`]+)`/g, "<code>$1</code>");
}

// Everything under `## <heading>` up to the next `##`.
function sectionLines(markdown, heading) {
	const lines = markdown.split("\n");
	const start = lines.findIndex((l) => l.trim().toLowerCase() === `## ${heading.toLowerCase()}`);
	if (start === -1) return [];
	const rest = lines.slice(start + 1);
	const end = rest.findIndex((l) => l.startsWith("## "));
	return (end === -1 ? rest : rest.slice(0, end)).map((l) => l.trim()).filter(Boolean);
}

function parseSyllabus(markdown) {
	const title = markdown.match(/^#\s+(.+)$/m)?.[1].trim() ?? "";
	const body = markdown.split("\n");
	const titleAt = body.findIndex((l) => /^#\s+/.test(l));
	const summary = body
		.slice(titleAt + 1)
		.find((l) => l.trim() && !l.startsWith("#")) ?? "";

	const sections = sectionLines(markdown, "Sections")
		.filter((line) => /^- \[[ xX]\]/.test(line))
		.map((line) => {
			const done = /^- \[[xX]\]/.test(line);
			const rest = line.replace(/^- \[[ xX]\]\s*/, "");
			const number = Number(rest.match(/^(\d+)\./)?.[1]);
			return { done, number, text: rest.replace(/^\d+\.\s*/, "") };
		});

	return { title, summary: summary.trim(), sections };
}

function parseWeakSpots(markdown) {
	return sectionLines(markdown, "Weak Spots")
		.filter((line) => line.startsWith("- "))
		.map((line) => line.slice(2).trim())
		.filter((line) => !/^none\b/i.test(line));
}

function lessonLink(slug, number) {
	if (!Number.isInteger(number)) return null;
	const dir = path.join(topicsDir, slug, "lessons");
	if (!fs.existsSync(dir)) return null;
	const file = fs.readdirSync(dir).find((name) => name.startsWith(`${number}-`) && name.endsWith(".html"));
	return file ? `topics/${slug}/lessons/${file}` : null;
}

function renderTopic(slug) {
	const syllabus = parseSyllabus(read(path.join(topicsDir, slug, "syllabus.md")));
	if (!syllabus.title) return "";

	const weakSpots = parseWeakSpots(read(path.join(topicsDir, slug, "journal.md")));
	const done = syllabus.sections.filter((s) => s.done).length;
	const total = syllabus.sections.length;
	const percent = total > 0 ? Math.round((done / total) * 100) : 0;

	const sections = syllabus.sections.map((section) => {
		const [, bold, outcome] = section.text.match(/^\*\*(.+?)\*\*\s*(.*)$/s) ?? [];
		const title = escapeHtml(bold ?? section.text);
		const href = lessonLink(slug, section.number);
		const label = href ? `<a href="${href}">${title}</a>` : `<strong>${title}</strong>`;
		return `<li class="${section.done ? "done" : ""}">
	<span class="box">${section.done ? "✓" : ""}</span>
	<span class="num">${section.number || ""}</span>
	<span class="text">${label} ${inlineMarkdown(outcome ?? "")}</span>
</li>`;
	}).join("\n");

	const weak = weakSpots.length === 0 ? "" : `<div class="weak">
	<h3>Weak spots</h3>
	<ul>${weakSpots.map((w) => `<li>${inlineMarkdown(w)}</li>`).join("")}</ul>
</div>`;

	return `<article class="card">
	<h2>${escapeHtml(syllabus.title)}</h2>
	<p class="summary">${inlineMarkdown(syllabus.summary)}</p>
	<div class="progress">
		<div class="bar"><span style="width:${percent}%"></span></div>
		<span class="count">${done} / ${total}</span>
	</div>
	<ul class="sections">
${sections}
	</ul>
	${weak}
</article>`;
}

const slugs = fs.existsSync(topicsDir)
	? fs.readdirSync(topicsDir, { withFileTypes: true })
		.filter((e) => e.isDirectory())
		.map((e) => e.name)
		.sort()
	: [];

const cards = slugs.map(renderTopic).filter(Boolean);
const n = cards.length;
const plural = n === 1 ? "" : "s";

const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Learning Index</title>
<style>${style}</style>
</head>
<body>
<main>
<h1>Learning Index</h1>
<p class="lede">${n} topic${plural} · generated by <code>npm run index:build</code></p>
${n > 0 ? cards.join("\n") : `<p class="empty">No topics yet.</p>`}
</main>
</body>
</html>
`;

fs.writeFileSync(outPath, html);
console.log(`Built → ${path.relative(root, outPath)} (${n} topic${plural})`);
